public class Output{
	public static void main(String[] args){
		System.out.println("Hello everyone, this is my first Java code");
		System.out.println("Teaching Java is Fun");
		System.out.print("Here i am using the print method");
		System.out.print("This text will be appended");
		System.out.printf("%nMercy Ben is %d years old.%n", 25);
		System.out.printf("My account balance is $%,.2f%n",76539999.922276);
	}
}