public class JavaTerms{
	public static void main(String[] args){
		System.out.println("abstract - Used to create incomplete classes and methods");
		System.out.println("assert - Used for debugging and testing assumptions");
		System.out.println("boolean - Used to store true or false values");
		System.out.println("break - Used to exit a loop or switch statement");
		System.out.println("byte - Used to store small integer values");
		System.out.println("case - Used in switch statements");
		System.out.println("catch - Used to handle exceptions");
		System.out.println("char - Used to store a single character");
		System.out.println("class - Used to define a class");
		System.out.println("continue - Used to skip to the next loop iteration");
		System.out.println("default - Used as the default case in switch");
		System.out.println("do - Used in do-while loops");
		System.out.println("double - Used to store decimal numbers");
		System.out.println("else - Used when an if condition is false");
		System.out.println("enum - Used to define a fixed set of constants");
		System.out.println("extends - Used for inheritance");
		System.out.println("final - Used to prevent modification");
		System.out.println("finally - Used to execute code after try-catch");
		System.out.println("float - Used to store decimal values");
		System.out.println("for - Used to create loops");
		System.out.println("if - Used for decision making");
		System.out.println("implements - Used to implement interfaces");
		System.out.println("import - Used to include packages");
		System.out.println("instanceof - Used to test object types");
		System.out.println("int - Used to store integers");
		System.out.println("interface - Used to define a contract for classes");
		System.out.println("long - Used to store large integers");
		System.out.println("native - Used to call non-Java code");
		System.out.println("new - Used to create objects");
		System.out.println("package - Used to organize classes");
		System.out.println("private - Used to restrict access");
		System.out.println("protected - Used for controlled access");
		System.out.println("public - Used to allow access from anywhere");
		System.out.println("return - Used to return a value from a method");
		System.out.println("short - Used to store small integers");
		System.out.println("static - Used for class-level members");
		System.out.println("strictfp - Used for floating-point consistency");
		System.out.println("super - Used to refer to parent class members");
		System.out.println("switch - Used for multiple selections");
		System.out.println("synchronized - Used for thread safety");
		System.out.println("this - Used to refer to the current object");
		System.out.println("throw - Used to throw exceptions");
		System.out.println("throws - Used to declare exceptions");
		System.out.println("transient - Used to exclude fields from serialization");
		System.out.println("try - Used to handle exceptions");
		System.out.println("void - Used when no value is returned");
		System.out.println("volatile - Used for thread-safe variables");
		System.out.println("while - Used to create loops");
		System.out.println("true - Represents a true boolean value");
		System.out.println("false - Represents a false boolean value");
	}
}